### ISSUE TITLE
Are SYSPROF EE and PROFILE EE Used by FSLIST or XLIST?

### ISSUE THREAD

**Issue by marXtevens** [devhawala/mecaff#1]
I have "upgraded" to the VM/370 1.3 beta which contains the MECAFF enhancements. I have figured out how to set up EE more to my liking using the PROFILE EE file. 

I would like to have is the PREFIX ON, as a default, for FSLIST and XLIST, when they start. so I copied PROFILE EE A to FSLIST EE A, and modified it.

>****************************************************************
>*
>* FILENAME:    FSLIST EE
>* PURPOSE:     LOCAL CONFIGURATION OF FULLSCREEN FSLIST.
>* AUTHOR:      MARK A. STEVENS <XMAS@NETSCAPE.NET>
>* CREATED:     2021-02-04
>* MODIFIED:    2021-01-25 MAS  Modified from PROFILE EE.
>*
>****************************************************************
>* CMDLINE BOTTOM
>* CURRLINE TOP
>* INFOLINE BOTTOM
>* MSGLINE TOP
>* NUMBERS ON
>  PREFIX ON
>* SCALE TOP
>* TABSET 8 16 24 32 40 48 56 64 72 80
>* Changed for REXX: mixed case
>* FTDEFAULTS EXEC     V 72 M

Leaving use PREFIX ON active, but that doesn't seem to work. Suggestions?

**Comment by devhawala** [comment]
Hello,

yes, the prefix zone is one of the few things that can be configured for `FSLIST` in the profile. There is only one profile for this (as `EE`, `FSLIST`, `FSVIEW` etc. are in fact the same program): `PROFILE EE *` (where the first file found through the file mode is used). There should also be an `SYSPROF EE Y`, but this one should be left unchanged.

The key is that the configuration commands `INFOLINES`, `PF` and `PREFIX` have an optional "target" parameter indicating the subsystem configured. So `PREFIX FSLIST ON` in your file `PROFILE EE` should do what you want.

See pages 20/21 and 26/27 in the user manual for version 1.2.5

Greetings
Hans

**Comment by marXtevens** [comment]
Thank you. It helps to know, and to have the most recent documentation & code. I was referring to a version 0.9.7 document. 
Closed user error.
